#ifndef CONFIG_H
#define CONFIG_H

#define SERVER_PORT "8080"
#define DEFAULT_GET_LIMIT 10
#define CACHE_SIZE 1000
#define PAGE_SIZE 100
#define PAGES_IN_CACHE 10
#define QUEUE_CAPACITY 1024
#define WRITE_BATCH_SIZE 50

#endif
